name: game_launcher
description: "A professional game launcher built with Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

msix_config:
  display_name: Game Launcher
  publisher_display_name: Retournay Steve
  publisher: CN=TonNom
  identity_name: com.SRet.gamelauncher
  msix_version: 1.0.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- State Management ---
  flutter_riverpod: ^3.2.1

  # --- Persistance & Système ---
  sqflite_common_ffi: ^2.3.0+2
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_secure_storage: ^10.0.0 # Pour tes clés API BYOK
  encrypt: ^5.0.3 # Chiffrement des données sensibles

  # --- Réseau & API ---
  dio: ^5.4.1 # Préféré à http pour la gestion des intercepteurs IGDB
  url_launcher: ^6.3.0 # Ajouté pour les vidéos et liens Web

  # --- UI & UX ---
  window_manager: ^0.5.1
  system_tray: ^2.0.2
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  file_picker: ^10.3.10

  # --- Utilitaires ---
  logger: ^2.5.0
  intl: ^0.19.0 # Souvent nécessaire pour formater les dates de sortie (releaseDate)
  file: ^7.0.0
  win32: ^5.10.0
  ffi: ^2.2.0
  process: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  msix: ^3.16.13
  plugin_platform_interface: ^2.1.8
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
